# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # GitHub Actions
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: "07:00"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "pip" # GitHub Actions
    directory: "./file-hosts.sh/github"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: "07:00"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "npm" # GitHub Actions
    directory: "./blog"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: "07:00"
    pull-request-branch-name:
      separator: "-"


  - package-ecosystem: "gomod"
    directory: "/file-hosts.sh/cn-blocked-domain"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: "07:00"
    pull-request-branch-name:
      separator: "-"
      
  - package-ecosystem: "pip" # GitHub Actions
    directory: "./file-hosts.sh/bilibili"
    schedule:
      interval: "daily"
      timezone: "Asia/Shanghai"
      time: "07:00"
    pull-request-branch-name:
      separator: "-"
