# This is a basic workflow to help you get started with Actions

name: ad-hosts-sqlist

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
   - cron: "0 */6 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
      # Runs a single command using the runners shell
      - name:  Build AdHosts
        run: |
          bash ./file-hosts.sh/ad-hosts-sqlist.sh
      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: ad-hosts-sqlist
          file: ./ad-*
          file_glob: true
          overwrite: true
          body: "update ad-hosts-sqlist"

      - name:  Build dns
        run: |
           bash ./file/bash/github-dns.sh
      
       - name:  push ad-hosts-coding
        run: |
           curl -sSL -u ${{ secrets.user }}:${{ secrets.password }} -T "{ad-hosts.txt,ad-adblock.txt,ad-adguardhome.txt,ad-clash.yaml,ad-clash-premium.yaml,ad-dnsmasq.conf,ad-domains.txt,ad-quantumult.yaml,ad-shadowrocket.list,ad-smartdns.conf,ad-surge.yaml,ad-unbound.conf,ad-bind9.conf,ad-adguardhome-dnstype.txt}" https://${{ secrets.web }}/ad-hosts/ad-hosts-sqlist/
        continue-on-error: true
