# This is a basic workflow to help you get started with Actions

name: Hosts-youtube

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
   - cron: "0 */12 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
      # Runs a single command using the runners shell
      - name:  Build AdHosts
        run: |
          bash ./file-hosts.sh/ad-youtube-hosts.sh
      - name:  push ad-hosts-coding
        run: |
          curl -u ${{ secrets.user }}:${{ secrets.password }} -T "{ad-youtube-adblock.txt,ad-youtube-adguardhome-dnstype.txt,ad-youtube-adguardhome.txt,ad-youtube-clash.yaml,ad-youtube-clash-premium.yaml,ad-youtube-dnsmasq.conf,ad-youtube-domains.txt,ad-youtube-hosts.txt,ad-youtube-quantumult.yaml,ad-youtube-shadowrocket.list,ad-youtube-smartdns.conf,ad-youtube-surge.yaml,ad-youtube-unbound.conf,ad-youtube-bind9.conf}" https://${{ secrets.web }}/ad-youtube-hosts/
        continue-on-error: true

    # 删除无用 workflow runs;
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 0.1
