# This is a basic workflow to help you get started with Actions

name: Allow

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
      # Runs a single command using the runners shell
      - name:  Build dns
        run: |
           bash ./file/bash/github-dns.sh
      - name:  Build Allow
        run: |
          bash ./file-hosts.sh/allow.sh
      - name: update github
        run: |
          cp allow.txt ./allow/allow.txt
          git remote rm origin
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
          git gc --aggressive
          git add ./allow/allow.txt
          git commit -m "update allow $(date +%Y.%m.%d.%H.%M)"
          git push -f -u origin main
      - name: commit and push
        id: commit
        run: |
         curl -sSL -u ${{ secrets.user }}:${{ secrets.password }} -T allow.txt https://${{ secrets.web }}/allow/
        continue-on-error: true
