# This is a basic workflow to help you get started with Actions

name: bilibili-Hosts

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.0]

    steps:
      - uses: actions/checkout@main
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@main
        with:
         python-version: ${{ matrix.python-version }}

      # Runs a single command using the runners shell
      - name:  Build bilibili
        run: |
          python ./file-hosts.sh/bilibili-cdn.py
      #- name:  push ad-hosts-coding
      #  run: |
      #    cp ./ad-edge-hosts.txt ./ad-hosts/ad-edge-hosts.txt
      #    git remote rm origin
      #    git config --local user.name "github-actions[bot]"
      #    git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #    git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
      #    git gc --aggressive
      #    git add ./ad-hosts/ad-edge-hosts.txt
      #    git commit -m "update ad-edge-hosts $(date +%Y.%m.%d.%H.%M)"
      #    git push -f -u origin main
      #  continue-on-error: true
      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: github-hosts
          file: ./bilibili-cdn.txt
          file_glob: true
          overwrite: true
          body: "update github-hosts"
