name: cn-blocked-domain
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@main
        with:
          go-version: ^1.20

      - name: Checkout codebase
        uses: actions/checkout@main
        
      - name:  Build dns
        run: |
          bash ./file/bash/github-dns.sh
          
      - name: Get cn-blocked-domain & run
        run: |
          cd ./file-hosts.sh/cn-blocked-domain
          go run ./

      #- name: Git push
      #  run: |
      #    cp ./cn-blocked-domain/publish/ip.txt ./Domains/cn-blocked-domain/
      #    cp ./cn-blocked-domain/publish/domains.txt ./Domains/cn-blocked-domain/
      #    cp ./cn-blocked-domain/publish/raw.txt ./Domains/cn-blocked-domain/
      #    git remote rm origin
      #    git config --local user.name "github-actions[bot]"
      #    git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #    git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
      #    git gc --aggressive
      #    git add ./Domains/cn-blocked-domain/
      #    git commit -m "update cn-blocked-domain txt $(date +%Y.%m.%d.%H.%M)"
      #    git push -f -u origin main
      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: cn-blocked-domain
          file: ./file-hosts.sh/cn-blocked-domaincn-blocked-domain/publish/*
          file_glob: true
          overwrite: true
          body: "update cn-blocked-domain"
