# This is a basic workflow to help you get started with Actions

name: DHDb-1

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

# A workflow run is mDnsh up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
      - name: update
        run: |
                  sudo apt install jq whois -y
       # Runs a single command using the runners shell
      - name:  Build GFWList2DHDb(1)
        run: |
          bash ./file-hosts.sh/DHDb-1.sh
      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: DHDb-1
          file: ./dhdb-*
          file_glob: true
          overwrite: true
          body: "update DHDb-1"
