# This is a basic workflow to help you get started with Actions

name: DnsHosts-adgh-trli

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

# A workflow run is mDnsh up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
       # Runs a single command using the runners shell
      - name:  Build GFWList2AGH
        run: |
          bash ./file-hosts.sh/dns-hosts/dns-adgh-trli.sh
      - name:  name GFWList2AGH
        run: |
            mv ./dns-adguardhome/blacklist_full.txt ./dnshosts-adgh-trli-blacklist_full.txt
            mv ./dns-adguardhome/blacklist_full_combine.txt ./dnshosts-adgh-trli-blacklist_full_combine.txt
            mv ./dns-adguardhome/whitelist_full.txt ./dnshosts-adgh-trli-whitelist_full.txt
            mv ./dns-adguardhome/whitelist_full_combine.txt ./dnshosts-adgh-trli-whitelist_full_combine.txt
            mv ./dns-adguardhome_new/blacklist_full.txt ./dnshosts-adgh-trli-new-blacklist_full.txt
            mv ./dns-adguardhome_new/blacklist_full_combine.txt ./dnshosts-adgh-trli-new-blacklist_full_combine.txt
            mv ./dns-adguardhome_new/whitelist_full.txt ./dnshosts-adgh-trli-new-whitelist_full.txt
            mv ./dns-adguardhome_new/whitelist_full_combine.txt ./dnshosts-adgh-trli-new-whitelist_full_combine.txt
      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: dns-hosts-adgh-trli
          file: ./dnshosts-adgh-trli*
          file_glob: true
          overwrite: true
          body: "update dns-hosts-adgh-trli"
