# This is a basic workflow to help you get started with Actions

name: DnsHosts-all-test

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

# A workflow run is mDnsh up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
       # Runs a single command using the runners shell

      - name:  Build dns
        run: |
          bash ./file/bash/github-dns.sh

      - name:  Build GFWList2AGH
        run: |
          python ./file-hosts.sh/dns-hosts/dns-test.sh

      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: dns-hosts-all-test
          file: ./hosts-dns/output/dnshosts-all-*
          file_glob: true
          overwrite: true
          body: "update dns-hosts-all"
