# This is a basic workflow to help you get started with Actions

name: DnsHosts-trli

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

# A workflow run is mDnsh up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
       # Runs a single command using the runners shell
      - name:  Build trli-dns.bash
        run: |
          echo -e "AdGuard Home_new"
          bash ./file-hosts.sh/dns-hosts/trli-dns/trli-dns.sh
      - name:  name trli-dns
        run: |
            mv ./dns-adguardhome_new/blacklist_full.txt ./dnshosts-adgh-trli-new-blacklist_full.txt
            mv ./dns-adguardhome_new/blacklist_full_combine.txt ./dnshosts-adgh-trli-new-blacklist_full_combine.txt
            mv ./dns-adguardhome_new/whitelist_full.txt ./dnshosts-adgh-trli-new-whitelist_full.txt
            mv ./dns-adguardhome_new/whitelist_full_combine.txt ./dnshosts-adgh-trli-new-whitelist_full_combine.txt
            mv ./dns-unbound/blacklist_full.conf ./dnshosts-all-unbound-blacklist_full.conf
            mv ./dns-unbound/whitelist_full.conf ./dnshosts-all-unbound-whitelist_full.conf
            mv ./dns-bind9/blacklist_full.conf ./dnshosts-all-bind9-blacklist_full.conf
            mv ./dns-bind9/whitelist_full.conf ./dnshosts-all-bind9-whitelist_full.conf
      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: dns-trli
          file: ./dnshosts-*
          file_glob: true
          overwrite: true
          body: "update dns-trli"
