# This is a basic workflow to help you get started with Actions

name: DnsHosts-trli-ip

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

# A workflow run is mDnsh up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
       # Runs a single command using the runners shell
      - name:  Build GFWList2AGH
        run: |
          bash ./file-hosts.sh/dns-hosts/dns-adgh-trli-ip.sh

      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: dns-hosts-trli-ip
          file: ./hosts-dns/output/dns-adguardhome_new/dnshosts-all*
          file_glob: true
          overwrite: true
          body: "update dns-hosts-trli-ip"
