name: docker-warp-cli

on:
  workflow_dispatch:
    schedule:
       - cron: "0 0 * *  */7"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - name: Checkout repository
        uses: actions/checkout@main

        
      - name: Setup QEMU
        uses: docker/setup-qemu-action@master

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Log into registry 
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Prepare
        id: prepare
        run: |
            echo ::set-output name=docker_platforms::linux/amd64
            echo ::set-output name=docker_image::${{ secrets.DOCKER_USERNAME }}/warp-cil      

      - name: Build Docker image
        id: build-image
        run: |
          cd ./dockerfile.sh/warp-cli
          docker buildx build  --platform ${{ steps.prepare.outputs.docker_platforms }} \
            --output "type=image,push=true" \
            --tag ${{ steps.prepare.outputs.docker_image }}:latest \
            --file Dockerfile \

      - name: Get WARP client version
        id: get-warp-client-version
        run: |
          echo "WARP_VERSION=$(docker run --rm --entrypoint='' ${{ steps.prepare.outputs.docker_image }}:latest warp-cli --version | cut -d ' ' -f 2)" >> "$GITHUB_OUTPUT"

      - name: Tag Docker image
        id: tag-image
        run: |
          docker tag ${{ steps.prepare.outputs.docker_image }}:latest

      - name: Push Docker image
        id: push-image
        run: |
          docker push ${{ steps.prepare.outputs.docker_image }}:latest