name: git-clean
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  git-clean:
    runs-on: ubuntu-latest
    steps:
      - name: Git push 
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote rm origin
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
          git for-each-ref --format='delete %(refname)' refs/original | git update-ref --stdin    
          git reflog expire --expire=now --all
          git gc --prune=now
          rm -rf .git/refs/original
          git reflog expire --expire=now --all
          git gc --prune=now
          git gc --aggressive --prune=now
          git gc --aggressive
          git add .
          git commit -m "$(date +%Y%m%d%H%M)"
          git push -f -u origin main
