name: Github-dnstype

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13.0-beta.3]

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}

    - name:  Build dns
      run: |
       bash ./file/bash/github-dns.sh

    - name: Install dependencies
      run: |
        cd file-hosts.sh/dnstype.txt
        python -m pip install --upgrade pip
        if [ -f requirements.txt  ]; then pip install -r requirements.txt; fi

    - name: update Accelerate-hosts-dnstype
      run: |
        python ./file-hosts.sh/dnstype.txt/dnstype-hosts.py

    - name: update bilibili-hosts-dnstype
      run: |
        python ./file-hosts.sh/dnstype.txt/dnstype-bilibili.py

    - name: update gfw-hosts-dnstype
      run: |
        python ./file-hosts.sh/dnstype.txt/dnstype-gfw.py

    #- name: update github
     # run: |
      #   cp ./file-hosts.sh/github/Accelerate-Hosts.txt ./Domains/AccelerateHosts/github-hosts.txt
       #  git remote rm origin
        # git config --local user.name "github-actions[bot]"
         #git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
        # git gc --aggressive
         #git add ./Domains/AccelerateHosts/github-hosts.txt 
         #git commit -m "update github-hosts $(date +%Y.%m.%d.%H.%M)"
         #git push -f -u origin main
    - name: Release Accelerate-hosts-dnstype
      uses: svenstaro/upload-release-action@master
      with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: github--dnstype
          file: ./file-hosts.sh/dnstype.txt/Accelerate-Hosts-dnstype.txt
          file_glob: true
          overwrite: true
          body: "update github-hosts"
    
    - name: Release bilibili-hosts-dnstype
      uses: svenstaro/upload-release-action@master
      with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: github--dnstype
          file: ./file-hosts.sh/dnstype.txt/bilibili-Hosts-dnstype.txt
          file_glob: true
          overwrite: true
          body: "update github-hosts"

    - name: Release gfw-hosts-dnstype
      uses: svenstaro/upload-release-action@master
      with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: github--dnstype
          file: ./file-hosts.sh/dnstype.txt/gfw-Hosts-dnstype.txt
          file_glob: true
          overwrite: true
          body: "update github-hosts"
