0name: GithubHosts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11.0]

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd file-hosts.sh/github
        python -m pip install --upgrade pip
        if [ -f requirements.txt  ]; then pip install -r requirements.txt; fi
    - name:  Build dns
      run: |
        bash ./file/dns/dns.sh
    - name: update hosts
      run: |
        sh ./file-hosts.sh/github/hosts.sh
    - name: update github
      run: |
         cp ./file-hosts.sh/github/Accelerate-Hosts.txt ./github-hosts/Accelerate-Hosts.txt
         git remote rm origin
         git config --global user.name root
         git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
         git gc --aggressive
         git add ./github-hosts/Accelerate-Hosts.txt
         git commit -m "update github $(date +%Y.%m.%d.%H.%M)"
         git push -f -u origin main
    - name: commit and push
      id: commit
      run: |
        curl -sSL --connect-time 3  --max-time 2 -u ${{ secrets.user }}:${{ secrets.password }} -T "{./file-hosts.sh/github/Accelerate-Hosts.txt}" https://${{ secrets.web }}/github/
      continue-on-error: true

    # 删除无用 workflow runs;
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 0.1
        keep_minimum_runs: 1
