name: go-update(cn-blocked-domain)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@main
        with:
          go-version: ^1.20
      - name: Checkout codebase
        uses: actions/checkout@main

      - name: go
        run: |
          cd ./file-hosts.sh/cn-blocked-domain
          go mod tidy -compat=1.20
          gofmt -w -r 'interface{} -> any' .
          go get -u
          go mod download
      - name: Git push 
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote rm origin
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
          git gc --aggressive
          git add ./file-hosts.sh/cn-blocked-domain 
          git commit -m "$(date +%Y%m%d%H%M)"
          git push -f -u origin main