# This is a basic workflow to help you get started with Actions

name: pDNSf-Hosts

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main
      # Runs a single command using the runners shell
      - name:  Build pDNSf-Hosts
        run: |
          bash ./file-hosts.sh/pDNSf-Hosts.sh
          
      - name: update github
        run: |
          cp pDNSf-hosts.txt ./ad-hosts/pDNSf-hosts/pDNSf-hosts.txt
          git remote rm origin
          git config --global user.name root
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
          git gc --aggressive
          git add ./ad-hosts/pDNSf-hosts/pDNSf-hosts.txt
          git commit -m "update pDNSf-hosts $(date +%Y.%m.%d.%H.%M)"
          git push -f -u origin main
          
      - name:  Build dns
        run: |
          bash ./file/bash/github-dns.sh
      - name:  push ad-hosts-coding
        run: |
          curl -sSL  -u ${{ secrets.user }}:${{ secrets.password }} -T "{pDNSf-hosts.txt}" https://${{ secrets.web }}/pDNSf-hosts/
        continue-on-error: true

    # 删除无用 workflow runs;
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 0.1
          keep_minimum_runs: 1
