name: cn-blocked-domain
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.x.y
        uses: actions/setup-go@main
        with:
          go-version: ^1.19.5

      - name: Checkout codebase
        uses: actions/checkout@main
        
      - name:  Build dns
        run: |
          bash ./file/bash/github-dns.sh
          
      - name: Get cn-blocked-domain & run
        run: |
          git clone https://github.com/potterli20/cn-blocked-domain
          cd cn-blocked-domain
          go run ./

      - name: Git push
        run: |
          cp ./cn-blocked-domain/publish/ip.txt ./Domains/cn-blocked-domain/
          cp ./cn-blocked-domain/publish/domains.txt ./Domains/cn-blocked-domain/
          cp ./cn-blocked-domain/publish/raw.txt ./Domains/cn-blocked-domain/
          git remote rm origin
          git config --global user.name root
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ github.repository }}"
          git gc --aggressive
          git add ./Domains/cn-blocked-domain/
          git commit -m "update cn-blocked-domain txt $(date +%Y.%m.%d.%H.%M)"
          git push -f -u origin main

    # 删除无用 workflow runs;
      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 0.1
          keep_minimum_runs: 1
